### ISSUE TITLE
Updating local storage object wipes other off

### ISSUE THREAD

**Issue by ux-leap** [zevero/simpleWebstorage#4] opened 2017-04-13 02:19 UTC
Hi 

Let's say my object is:

`'myKey',{a:[1,2,5], b: 'ok', c: 'www'}`

and I would like to update only one key value

`localStorage.set('myKey',{c: 'www'})`

this will wipe off other keys. It will be good if you can add an update option so my other keys will say untouched.

eg `localStorage.update('myKey',{c: 'rrr'})`

result 

`'myKey',{a:[1,2,5], b: 'ok', c: 'rrr'}`

Thanks

**Comment by zevero** [comment] 2017-04-13 09:26
Good idea ... do you have a good implementation like $.extend ?
I googled for
http://stackoverflow.com/questions/11197247/javascript-equivalent-of-jquerys-extend-method
https://j11y.io/jquery/#v=1.6.2&fn=jQuery.extend
https://jsfiddle.net/1vrkw1pc/
https://gomakethings.com/vanilla-javascript-version-of-jquery-extend/

Should we support a deep flag?

You see the problem is not trivial ... so maybe we should keep things simple and let the user do updating ... whats your opinion?

**Comment by zevero** [comment] 2017-04-13 09:27
I think most robust way is to steal from jQuery
https://j11y.io/jquery/#v=git&fn=jQuery.extend

**Comment by ux-leap** [comment] 2017-04-13 09:32
Yeah I agree. for now I dit a simple function:

```
var updateFilter = function (key, value) {
  var getStorage = localStorage.get('myKey')
  getStorage.historyFilter[key] = value
  localStorage.set('myKey', getStorage)
}
```

but this way I can only update one key at time and nesting is quite tricky.

**Comment by zevero** [comment] 2017-04-13 09:45
we could use this
https://jsfiddle.net/1vrkw1pc/
it has no checks ... but is otherwise very performant

**Comment by ux-leap** [comment] 2017-04-13 09:48
Yeah go for it. I've got plenty use cases for it. Thanks

**Comment by zevero** [comment] 2017-04-13 10:08
Ok I have committed but not tested ...

Would you be so kind and test it?

**Comment by ux-leap** [comment] 2017-04-13 12:24
Hi your tweak dos not work. There was some typo with the closing brackets but even after the fix there is some issue with it...here is my test: https://jsbin.com/pocegocini/edit?js,console,output

**Comment by zevero** [comment] 2017-04-13 12:44
It does work, if you use localStorage.extend instead of localStorage.set at your last statment :-)

But ... as you can see, you may not want to do recursive extend, since for example maxResults stays present after extending ...

**Comment by ux-leap** [comment] 2017-04-13 12:59
ah yes...ok I've tested on my proper code and it works just fine. I think there was only one missing bracket. Thanks zavero

**Comment by zevero** [comment] 2017-04-13 13:17
I have done a new commit with updated readme using assign.
This will make a shallow copy and I think this is easiest for everyone to understand.
The former extend was not very clear on what it actually merged ... so merging {a:[1,2,3]} and {a:[4,5]} would result in  {a:[4,5,3]}

**Comment by zevero** [comment] 2017-04-13 13:25
Ok ... new and hopefully last commit with checks for object

**Closed as completed** 2017-04-13 13:31 UTC

**Comment by ux-leap** [comment] 2017-04-13 22:06
Hmm I think assign does not work with nested objects: https://jsbin.com/nayogukoga/1/edit?js,console,output

**Comment by zevero** [comment] 2017-04-13 22:42
Yes, Object.assign only does shallow merge, which - I think - is quite sensible ... otherwise - as in your example maxResults leaks into the newly merged Object ...

I did not like extend so much as arrays get mixed up... but I checked now $.extend(true,{a:[3,5,6]},{a:[1,2]}) is {a:[1,2,6]} as well... not convining.

Well propose, what we should do ...

**Comment by ux-leap** [comment] 2017-04-14 04:11
`$.extend(true,{a:[3,5,6]},{a:[1,2]}) is {a:[1,2,6]}` to me this is exactly how it should be. We are only updating the keys. When the third one is untouched means it stays as it was. To me this is exactly what I was looking for. Imagine defaults saved in a object loaded up front and saved in local storage than you can change default variables on the fly and not changing others.

**Comment by zevero** [comment] 2017-04-15 15:08
So ... but should we integrate this into simpleWebstorage? I personally always use jQuery or other frameworks, which allow me to do object merges ... and I just would use those ... no need to quadruple the size of this module ... I liked Object.assign for this reason, very simple.
I still can revert for my former extend function, but I am not sure if we should ... what is your view of that?
